language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit --tap --coverage-clover build/logs/clover.xml

after_script:
  - bash bin/codeclimate.sh
